<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Kuulla.FeedPoller</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kuulla.Core\Kuulla.Core.csproj" />
    <ProjectReference Include="..\Kuulla.ServiceDefaults\Kuulla.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.Azure.Cosmos" Version="13.5.3" />
  </ItemGroup>

</Project>
